# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from devbot_navigation/wheel_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class wheel_info(genpy.Message):
  _md5sum = "da1f1150c07550c7f87dd0a67c7a0fac"
  _type = "devbot_navigation/wheel_info"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 wheel_volt_R
int64 wheel_volt_L
float64 wheel_cmd_R
float64 wheel_cmd_L
float64 wheel_vel_R
float64 wheel_vel_L"""
  __slots__ = ['wheel_volt_R','wheel_volt_L','wheel_cmd_R','wheel_cmd_L','wheel_vel_R','wheel_vel_L']
  _slot_types = ['int64','int64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       wheel_volt_R,wheel_volt_L,wheel_cmd_R,wheel_cmd_L,wheel_vel_R,wheel_vel_L

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(wheel_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.wheel_volt_R is None:
        self.wheel_volt_R = 0
      if self.wheel_volt_L is None:
        self.wheel_volt_L = 0
      if self.wheel_cmd_R is None:
        self.wheel_cmd_R = 0.
      if self.wheel_cmd_L is None:
        self.wheel_cmd_L = 0.
      if self.wheel_vel_R is None:
        self.wheel_vel_R = 0.
      if self.wheel_vel_L is None:
        self.wheel_vel_L = 0.
    else:
      self.wheel_volt_R = 0
      self.wheel_volt_L = 0
      self.wheel_cmd_R = 0.
      self.wheel_cmd_L = 0.
      self.wheel_vel_R = 0.
      self.wheel_vel_L = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2q4d().pack(_x.wheel_volt_R, _x.wheel_volt_L, _x.wheel_cmd_R, _x.wheel_cmd_L, _x.wheel_vel_R, _x.wheel_vel_L))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.wheel_volt_R, _x.wheel_volt_L, _x.wheel_cmd_R, _x.wheel_cmd_L, _x.wheel_vel_R, _x.wheel_vel_L,) = _get_struct_2q4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2q4d().pack(_x.wheel_volt_R, _x.wheel_volt_L, _x.wheel_cmd_R, _x.wheel_cmd_L, _x.wheel_vel_R, _x.wheel_vel_L))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.wheel_volt_R, _x.wheel_volt_L, _x.wheel_cmd_R, _x.wheel_cmd_L, _x.wheel_vel_R, _x.wheel_vel_L,) = _get_struct_2q4d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2q4d = None
def _get_struct_2q4d():
    global _struct_2q4d
    if _struct_2q4d is None:
        _struct_2q4d = struct.Struct("<2q4d")
    return _struct_2q4d
