// Generated by gencpp from file devbot_teleop/CMD.msg
// DO NOT EDIT!


#ifndef DEVBOT_TELEOP_MESSAGE_CMD_H
#define DEVBOT_TELEOP_MESSAGE_CMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace devbot_teleop
{
template <class ContainerAllocator>
struct CMD_
{
  typedef CMD_<ContainerAllocator> Type;

  CMD_()
    : direction()  {
    }
  CMD_(const ContainerAllocator& _alloc)
    : direction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::devbot_teleop::CMD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::devbot_teleop::CMD_<ContainerAllocator> const> ConstPtr;

}; // struct CMD_

typedef ::devbot_teleop::CMD_<std::allocator<void> > CMD;

typedef boost::shared_ptr< ::devbot_teleop::CMD > CMDPtr;
typedef boost::shared_ptr< ::devbot_teleop::CMD const> CMDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::devbot_teleop::CMD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::devbot_teleop::CMD_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::devbot_teleop::CMD_<ContainerAllocator1> & lhs, const ::devbot_teleop::CMD_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::devbot_teleop::CMD_<ContainerAllocator1> & lhs, const ::devbot_teleop::CMD_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace devbot_teleop

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::devbot_teleop::CMD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::devbot_teleop::CMD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::devbot_teleop::CMD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::devbot_teleop::CMD_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devbot_teleop::CMD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::devbot_teleop::CMD_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::devbot_teleop::CMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "326e9417def5db9a05a2704a4d8de15e";
  }

  static const char* value(const ::devbot_teleop::CMD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x326e9417def5db9aULL;
  static const uint64_t static_value2 = 0x05a2704a4d8de15eULL;
};

template<class ContainerAllocator>
struct DataType< ::devbot_teleop::CMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "devbot_teleop/CMD";
  }

  static const char* value(const ::devbot_teleop::CMD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::devbot_teleop::CMD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
;
  }

  static const char* value(const ::devbot_teleop::CMD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::devbot_teleop::CMD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CMD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::devbot_teleop::CMD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::devbot_teleop::CMD_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEVBOT_TELEOP_MESSAGE_CMD_H
