// Generated by gencpp from file base_controller_twist_converter/vel_data.msg
// DO NOT EDIT!


#ifndef BASE_CONTROLLER_TWIST_CONVERTER_MESSAGE_VEL_DATA_H
#define BASE_CONTROLLER_TWIST_CONVERTER_MESSAGE_VEL_DATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_controller_twist_converter
{
template <class ContainerAllocator>
struct vel_data_
{
  typedef vel_data_<ContainerAllocator> Type;

  vel_data_()
    : linear_velocity(0.0)
    , angular_velocity(0.0)  {
    }
  vel_data_(const ContainerAllocator& _alloc)
    : linear_velocity(0.0)
    , angular_velocity(0.0)  {
  (void)_alloc;
    }



   typedef double _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef double _angular_velocity_type;
  _angular_velocity_type angular_velocity;





  typedef boost::shared_ptr< ::base_controller_twist_converter::vel_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_controller_twist_converter::vel_data_<ContainerAllocator> const> ConstPtr;

}; // struct vel_data_

typedef ::base_controller_twist_converter::vel_data_<std::allocator<void> > vel_data;

typedef boost::shared_ptr< ::base_controller_twist_converter::vel_data > vel_dataPtr;
typedef boost::shared_ptr< ::base_controller_twist_converter::vel_data const> vel_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_controller_twist_converter::vel_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::base_controller_twist_converter::vel_data_<ContainerAllocator1> & lhs, const ::base_controller_twist_converter::vel_data_<ContainerAllocator2> & rhs)
{
  return lhs.linear_velocity == rhs.linear_velocity &&
    lhs.angular_velocity == rhs.angular_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::base_controller_twist_converter::vel_data_<ContainerAllocator1> & lhs, const ::base_controller_twist_converter::vel_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace base_controller_twist_converter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_controller_twist_converter::vel_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_controller_twist_converter::vel_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_controller_twist_converter::vel_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e55b2cec3678035367208627e07de350";
  }

  static const char* value(const ::base_controller_twist_converter::vel_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe55b2cec36780353ULL;
  static const uint64_t static_value2 = 0x67208627e07de350ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_controller_twist_converter/vel_data";
  }

  static const char* value(const ::base_controller_twist_converter::vel_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 linear_velocity\n"
"float64 angular_velocity\n"
;
  }

  static const char* value(const ::base_controller_twist_converter::vel_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vel_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_controller_twist_converter::vel_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_controller_twist_converter::vel_data_<ContainerAllocator>& v)
  {
    s << indent << "linear_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "angular_velocity: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_CONTROLLER_TWIST_CONVERTER_MESSAGE_VEL_DATA_H
