// Generated by gencpp from file mpu6050_imu_ros/mpu6050.msg
// DO NOT EDIT!


#ifndef MPU6050_IMU_ROS_MESSAGE_MPU6050_H
#define MPU6050_IMU_ROS_MESSAGE_MPU6050_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>

namespace mpu6050_imu_ros
{
template <class ContainerAllocator>
struct mpu6050_
{
  typedef mpu6050_<ContainerAllocator> Type;

  mpu6050_()
    : orientation()
    , body_rates()  {
    }
  mpu6050_(const ContainerAllocator& _alloc)
    : orientation(_alloc)
    , body_rates(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _body_rates_type;
  _body_rates_type body_rates;





  typedef boost::shared_ptr< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> const> ConstPtr;

}; // struct mpu6050_

typedef ::mpu6050_imu_ros::mpu6050_<std::allocator<void> > mpu6050;

typedef boost::shared_ptr< ::mpu6050_imu_ros::mpu6050 > mpu6050Ptr;
typedef boost::shared_ptr< ::mpu6050_imu_ros::mpu6050 const> mpu6050ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator1> & lhs, const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator2> & rhs)
{
  return lhs.orientation == rhs.orientation &&
    lhs.body_rates == rhs.body_rates;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator1> & lhs, const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mpu6050_imu_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d84bad830e0ca58f7358ace8e2e9beef";
  }

  static const char* value(const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd84bad830e0ca58fULL;
  static const uint64_t static_value2 = 0x7358ace8e2e9beefULL;
};

template<class ContainerAllocator>
struct DataType< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mpu6050_imu_ros/mpu6050";
  }

  static const char* value(const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Quaternion orientation\n"
"geometry_msgs/Vector3 body_rates\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.orientation);
      stream.next(m.body_rates);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mpu6050_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mpu6050_imu_ros::mpu6050_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mpu6050_imu_ros::mpu6050_<ContainerAllocator>& v)
  {
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
    s << indent << "body_rates: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.body_rates);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MPU6050_IMU_ROS_MESSAGE_MPU6050_H
